# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest' #vs2017-win2016 for docs

variables:
  solution: 'Rezolver.sln'
  docsProject: 'doc/Rezolver.Docs/Rezolver.Docs.csproj'
  buildPlatform: 'Any CPU'
  packageBuildConfig: 'Release'
  localPackageBuildConfig: 'Debug'
  docsBuildConfig: 'Documentation'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build Core'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(packageBuildConfig)'

- task: VSTest@2
  displayName: 'Run Unit Tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(packageBuildConfig)'
    testAssemblyVer2: |
        **\Rezolver.Tests.dll
        **\Rezolver.Microsoft.DependencyInjection.Tests.dll
        **\Rezolver.Tests.Compilation.Expressions.dll
        **\Rezolver.Tests.Examples.dll
        !**\obj\**
    otherConsoleOptions: '/Framework:.NETCoreApp,Version=v2.2'

- task: DotNetCoreCLI@2
  displayName: 'Package PreRelease'
  inputs:
    command: 'pack'
    searchPatternPack: '**\Rezolver\Rezolver.csproj;**\Rezolver.Microsoft.Extensions.DependencyInjection.csproj;**\Rezolver.Microsoft.AspNetCore.Hosting.csproj;**\Rezolver.Microsoft.Extensions.Hosting.csproj'
    configurationToPack: '$(packageBuildConfig)'
    nobuild: true
    buildProperties: 'VersionSuffix="CI-$(Build.BuildNumber)"'
    packDirectory: '$(Build.artifactStagingDirectory)\nupkg\pre'

- task: DotNetCoreCLI@2
  displayName: 'Package Final'
  inputs:
    command: 'pack'
    searchPatternPack: '**\Rezolver\Rezolver.csproj;**\Rezolver.Microsoft.Extensions.DependencyInjection.csproj;**\Rezolver.Microsoft.AspNetCore.Hosting.csproj;**\Rezolver.Microsoft.Extensions.Hosting.csproj'
    configurationToPack: '$(packageBuildConfig)'
    nobuild: true
    packDirectory: '$(Build.artifactStagingDirectory)\nupkg\final'

- task: DotNetCoreCLI@2
  displayName: 'Local Package PreRelease'
  inputs:
    command: 'pack'
    searchPatternPack: '**\Rezolver\Rezolver.csproj;**\Rezolver.Microsoft.Extensions.DependencyInjection.csproj;**\Rezolver.Microsoft.AspNetCore.Hosting.csproj;**\Rezolver.Microsoft.Extensions.Hosting.csproj'
    configurationToPack: '$(localPackageBuildConfig)'
    buildProperties: 'VersionSuffix="CI-$(Build.BuildNumber)"'
    packDirectory: '$(Build.artifactStagingDirectory)\nupkg\local-pre'

- task: DotNetCoreCLI@2
  displayName: 'Local Package Final'
  inputs:
    command: 'pack'
    searchPatternPack: '**\Rezolver\Rezolver.csproj;**\Rezolver.Microsoft.Extensions.DependencyInjection.csproj;**\Rezolver.Microsoft.AspNetCore.Hosting.csproj;**\Rezolver.Microsoft.Extensions.Hosting.csproj'
    configurationToPack: '$(localPackageBuildConfig)'
    packDirectory: '$(Build.artifactStagingDirectory)\nupkg\local-final'

- task: VSBuild@1
  displayName: 'Build documentation site'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(docsBuildConfig)'

- task: DotNetCoreCLI@2
  displayName: 'Zip Website'
  inputs:
    command: publish
    projects: '$(docsProject)'
    publishWebProjects: False
    arguments: '--configuration $(docsBuildConfig) --output $(Build.ArtifactStagingDirectory)\docs'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1