# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest' #vs2017-win2016 for docs

variables:
  solution: 'Rezolver.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorMain: '2'
  minorMain: '0'
  majorOther: '2'
  minorOther: '3'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: |
        **\Rezolver.Tests.dll
        **\Rezolver.Microsoft.DependencyInjection.Tests.dll
        **\Rezolver.Tests.Compilation.Expressions.dll
        **\Rezolver.Tests.Examples.dll
        !**\obj\**
    otherConsoleOptions: '/Framework:.NETCoreApp,Version=v2.2'

- task: DotNetCoreCLI@2
  displayName: 'Package Rezolver'
  inputs:
    command: 'pack'
    searchPatternPack: '**\Rezolver\Rezolver.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(majorMain)'
    minorVersion: '$(minorMain)'
    patchVersion: '$(rev:.r)'

- task: DotNetCoreCLI@2
  displayName: 'Package Others'
  inputs:
    command: 'pack'
    searchPatternPack: '**\Rezolver.Microsoft.Extensions.DependencyInjection.csproj;**\Rezolver.Microsoft.AspNetCore.Hosting.csproj;**\Rezolver.Microsoft.Extensions.Hosting.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(majorOther)'
    minorVersion: '$(minorOther)'
    patchVersion: '$(rev:.r)'

- task: PublishBuildArtifacts@1